// Custom client-side types for the mock application

export type Host = {
  id: string;
  name: string;
  email: string;
};

export type Participant = {
  id: string;
  name: string;
  email: string;
};

export type ChatMessage = {
  id: string;
  session_id: string; // Changed from workshop_id
  sender_id: string;
  sender_name: string;
  message: string;
  created_at: string;
};

export type Feedback = {
  interactive: number;
  helpful: number;
  overall: number;
};

export type Evaluation = {
  active: number;
  valueAdded: number;
  overall: number;
};

export type SessionParticipantRecord = {
  participant_id: string;
  attendance: 'pending' | 'present';
  feedback: Feedback | null;
  evaluation: Evaluation | null;
}

export type Session = {
  id: string;
  workshop_id: string;
  session_number: number;
  title: string;
  date: string;
  start_time: string;
  end_time: string;
  status: 'scheduled' | 'live' | 'ended';
  participant_records: SessionParticipantRecord[];
};

export type Workshop = {
  id: string;
  title: string;
  hosts: Host[];
  participants: Participant[];
  sessions: Session[];
};

// Simplified user type for client-side state
export interface SessionUser {
  id: string;
  name: string;
  email: string;
  role: 'manager' | 'host' | 'participant';
}

// AppContext type
export interface AppContextType {
  user: SessionUser | null;
  workshops: Workshop[];
  isLoading: boolean;
  login: (email: string, pass: string) => Promise<void>;
  logout: () => void;
  addWorkshop: (
    workshopData: { title: string; total_sessions: number; weekday: string; time: string },
    hosts: Omit<Host, 'id'>[], 
    participants: Omit<Participant, 'id'>[]
  ) => Promise<void>;
  updateWorkshop: (workshop: Workshop) => Promise<void>;
  updateSession: (session: Session) => Promise<void>;
}

// Placeholder types for Supabase to fix compilation error.
// In a real project, these would be generated by `supabase gen types typescript`.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      workshops: {
        Row: {
          id: string;
          title: string;
          date: string;
          start_time: string;
          end_time: string;
          status: "scheduled" | "live" | "ended";
        };
        Insert: {
          id?: string;
          title: string;
          date: string;
          start_time: string;
          end_time: string;
          status?: "scheduled" | "live" | "ended";
        };
        Update: {
          id?: string;
          title?: string;
          date?: string;
          start_time?: string;
          end_time?: string;
          status?: "scheduled" | "live" | "ended";
        };
      };
      hosts: {
        Row: {
          id: string;
          workshop_id: string;
          name: string;
          email: string;
        };
        Insert: {
          id?: string;
          workshop_id: string;
          name: string;
          email: string;
        };
        Update: {
          id?: string;
          workshop_id?: string;
          name?: string;
          email?: string;
        };
      };
      participants: {
        Row: {
          id: string;
          workshop_id: string;
          name: string;
          email: string;
          attendance: "pending" | "present";
          feedback: Json | null;
          evaluation: Json | null;
        };
        Insert: {
          id?: string;
          workshop_id: string;
          name: string;
          email: string;
          attendance?: "pending" | "present";
          feedback?: Json | null;
          evaluation?: Json | null;
        };
        Update: {
          id?: string;
          workshop_id?: string;
          name?: string;
          email?: string;
          attendance?: "pending" | "present";
          feedback?: Json | null;
          evaluation?: Json | null;
        };
      };
      chat_messages: {
        Row: {
          id: string;
          workshop_id: string;
          sender_id: string;
          sender_name: string;
          message: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          workshop_id: string;
          sender_id: string;
          sender_name: string;
          message: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          workshop_id?: string;
          sender_id?: string;
          sender_name?: string;
          message?: string;
          created_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
  };
}